# Generated by Django 6.0.2 on 2026-02-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_products_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='image',
            field=models.ImageField(upload_to='product_img/'),
        ),
    ]
