# Generated by Django 6.0.2 on 2026-02-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_productdetails_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.CharField()),
                ('old_price', models.CharField()),
                ('category_name', models.CharField()),
                ('image', models.ImageField(upload_to='product_img/')),
            ],
        ),
        migrations.CreateModel(
            name='TopCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.CharField()),
                ('old_price', models.CharField()),
                ('category_name', models.CharField()),
                ('image', models.ImageField(upload_to='product_img/')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.CharField()),
                ('old_price', models.CharField()),
                ('category_name', models.CharField()),
                ('image', models.ImageField(upload_to='product_img/')),
            ],
        ),
    ]
