# Generated by Django 6.0.2 on 2026-02-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mostplayed_topcategories_trendinggames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MostPlayed',
        ),
        migrations.DeleteModel(
            name='TopCategories',
        ),
        migrations.DeleteModel(
            name='TrendingGames',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='is_most_played',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='is_top_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
