# Generated by Django 6.0.2 on 2026-02-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_mostplayed_delete_topcategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='game_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='multi_tag',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
