# Generated by Django 6.0.2 on 2026-02-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_productdetails_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='is_most_played',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='is_top_category',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='is_trending',
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='category_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='game_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='genre',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='multi_tag',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='old_price',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.CharField(),
        ),
    ]
