# Generated by Django 6.0.2 on 2026-02-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contactmessage_delete_usermessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
