# Generated by Django 6.0.2 on 2026-02-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_userregister_alter_productdetails_category_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegister',
            new_name='UserSignUp',
        ),
    ]
