# Generated by Django 6.0.2 on 2026-02-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_userregister_usersignup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSignUp',
            new_name='SignUp',
        ),
    ]
