# Generated by Django 6.0.2 on 2026-02-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_usersignup_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='boolen_ofprices',
            field=models.BooleanField(default=False),
        ),
    ]
