# Generated by Django 6.0.2 on 2026-02-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_productdetails_is_free_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='boolen_of_prices',
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='genre',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='multi_tag',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='old_price',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
