# Generated by Django 6.0.2 on 2026-02-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_productdetails_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='game_id_txt',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='game_id',
            field=models.IntegerField(),
        ),
    ]
