# Generated by Django 6.0.2 on 2026-02-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_productdetails_a_alter_productdetails_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='a',
            new_name='Image 300x220:',
        ),
    ]
