# Generated by Django 6.0.2 on 2026-02-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_a_productdetails_image_300x220_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='Image 300x220:',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='image_formated',
            field=models.ImageField(default=1, upload_to='product_img/', verbose_name='Image 300x220'),
            preserve_default=False,
        ),
    ]
