# Generated by Django 6.0.2 on 2026-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_productdetails_image_300x220__and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.CharField(help_text='a', max_length=5),
        ),
    ]
