# Generated by Django 6.0.2 on 2026-02-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_productdetails_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.CharField(help_text='If you want make this free write: free also write into old_price: free', max_length=5),
        ),
    ]
