# Generated by Django 6.0.2 on 2026-02-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_productdetails_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('surname', models.CharField()),
                ('email', models.CharField()),
                ('subject', models.CharField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='old_price',
            field=models.CharField(help_text='If not have old price write: not_have', max_length=8),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.CharField(help_text='If you want make this free write: free <br> also write into old_price: free', max_length=5),
        ),
    ]
