# Generated by Django 6.0.2 on 2026-03-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_usermessage_alter_productdetails_old_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Trash Bin',
                'verbose_name_plural': 'Trash Bin',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='signup',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
