# Generated by Django 6.0.2 on 2026-02-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.CharField()),
                ('old_price', models.CharField()),
                ('description', models.TextField()),
                ('genre', models.CharField()),
                ('gmae_id', models.CharField()),
                ('multi_tag', models.CharField()),
                ('category_name', models.CharField()),
                ('image', models.ImageField(upload_to='product_img/')),
            ],
        ),
    ]
