# Generated by Django 6.0.2 on 2026-02-14 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='gmae_id',
            new_name='game_id',
        ),
    ]
