# Generated by Django 6.0.2 on 2026-02-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_passwordreset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='ProductDetails',
        ),
    ]
