# Generated by Django 6.0.2 on 2026-02-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='game_id',
            field=models.IntegerField(),
        ),
    ]
