# Generated by Django 6.0.2 on 2026-02-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_productdetails_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='category_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='name',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='old_price',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
