# Generated by Django 6.0.2 on 2026-02-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_productdetails_boolen_ofprices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='boolen_ofprices',
            new_name='boolen_of_prices',
        ),
    ]
