# Generated by Django 6.0.2 on 2026-02-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_boolen_ofprices_productdetails_boolen_of_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
