# Generated by Django 6.0.2 on 2026-02-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_productdetails_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='boolen_of_prices',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Free game'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
