# Generated by Django 6.0.2 on 2026-02-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_productdetails_boolen_of_prices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='is_free',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='boolen_of_prices',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='multi_tag',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='old_price',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
