# Generated by Django 6.0.2 on 2026-02-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_productdetails_boolen_of_prices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='game_id',
            field=models.CharField(max_length=20),
        ),
    ]
