# Generated by Django 6.0.2 on 2026-02-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_productdetails_game_id_txt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='a',
            field=models.ImageField(default=1, upload_to='product_img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
