# Generated by Django 6.0.3 on 2026-03-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.CharField(help_text='If you want make this free write: free <br> also write into old_price: free', max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
