# Generated by Django 6.0.3 on 2026-03-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactinfo_delete_productdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='location2',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
