# Generated by Django 6.0.3 on 2026-03-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactinfo_location2_contactinfo_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='time',
            new_name='email_description',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone_description',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
