# Generated by Django 6.0.3 on 2026-03-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_time_contactinfo_email_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactInfo',
            new_name='data',
        ),
    ]
