# Generated by Django 6.0.3 on 2026-03-15 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_contactinfo_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='ContactInfo',
        ),
    ]
