# Generated by Django 6.0.3 on 2026-03-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_data_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('star_count', models.IntegerField(default=0)),
            ],
        ),
    ]
