# Generated by Django 6.0.3 on 2026-03-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_carouseldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouseldata',
            name='dot_count',
            field=models.IntegerField(default=0),
        ),
    ]
