# Generated by Django 6.0.3 on 2026-03-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_carouseldata_dot_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselData',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='cheack_box',
            field=models.BooleanField(default=False),
        ),
    ]
