# Generated by Django 6.0.3 on 2026-03-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_usermessage_import_time_usermessage_user_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='cheack_box',
            new_name='check_box',
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='import_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
