# Generated by Django 6.0.3 on 2026-03-18 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_cheack_box_usermessage_check_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='import_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
