# Generated by Django 6.0.3 on 2026-03-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_usermessage_user_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='import_time',
        ),
    ]
