# Generated by Django 6.0.3 on 2026-03-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_usermessage_import_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='user_img',
        ),
    ]
